create table if not exists public.merchandise_drops (
  id bigint generated by default as identity primary key,
  source text not null,
  source_id text not null,
  title text not null,
  price_jpy integer,
  release_date text,
  image_url text,
  product_url text,
  status text not null default 'active' check (status in ('active', 'closed', 'sold_out')),
  raw_payload jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source, source_id)
);

create index if not exists merchandise_drops_active_idx
  on public.merchandise_drops (status, fetched_at desc);

alter table public.merchandise_drops enable row level security;

-- Add a narrowly scoped SELECT policy for the frontend's anon/authenticated role
-- only after deciding whether public inventory visibility is intended.
-- The service-role worker bypasses RLS for upserts.
